### PR TITLE
Fixes #42 - Log URL to the newly created spreadsheet

### LINKED ISSUE #42: Log out a URL to the newly created spreadsheet
I hate opening Gmail.

### PR DESCRIPTION
**Pull request by miketaylr**

### CODE REVIEW

**Comment by miketaylr** [comment]
r=me, just logging out a URL.

**Comment by miketaylr** [comment]
Ha, actually no. No super powers.

**Comment by past** [comment]
@miketaylr oh, I bet I know why you can't merge: this is a user-owned repo, not an organization-owned one. Should we transfer to webcompat or mozilla?

**Comment by miketaylr** [comment]
No strong preference, but probably Mozilla makes more sense.

**Pull request merged**
